### ISSUE TITLE
[GTK4] Navigation and rendering issues with fixed-layout documents with `page-spread-center`

### ISSUE THREAD

**Issue by initramfs** [johnfactotum/foliate#1072]
**Note:** Most of the problems below probably stem from [foliate-js](https://github.com/johnfactotum/foliate-js), which does seem to have a disclaimer claiming the FXL renderer is unfinished. At the very least this bug report can serve as implementation tests/milestones to complete the renderer.

---

For EPUB 3 [fixed-layout documents](https://www.w3.org/TR/epub-33/#sec-fixed-layouts) with a [page progression direction](https://www.w3.org/TR/epub-33/#attrdef-spine-page-progression-direction) of `rtl` (right to left) several rendering and navigation issues occur, as described below:

1. On opening the EPUB document, instead of the cover page being shown, a small white box is presented:
![Opening screenshot](https://github.com/johnfactotum/foliate/assets/3128050/87a56548-5f1e-4814-b500-dd8bb5064c92)
from this screen, neither the forward or backward navigation keys work to move the reader past this initial white box, only navigation directly via clicking the links in the navigation document work.<br/>
Advancing past this page (via clicking a link in the navigation document/TOC allows forward/backward navigation to work again) but it is possible to hit "previous" on the cover page, which will land back on this initial white box and break navigation again.

2. Rendering of [true spreads](https://www.w3.org/TR/epub-33/#page-spread) results in a center gap between the two pages:
![True spread gap screenshot](https://github.com/johnfactotum/foliate/assets/3128050/1916c467-7555-49f6-9cee-13af3905e683)
While section 8.2.2.4 of the EPUB 3.3 specification doesn't specify that a gap cannot be present, I believe the expected behaviour is for gapless rendering (as seen on other EPUB renderers like [Thorium](https://github.com/edrlab/thorium-reader)).

3. Rendering of [synthetic spreads](https://www.w3.org/TR/epub-33/#spread) with a 'gap' in the spread properties (e.g. `rendition:page-spread-right` followed by `rendition:page-spread-center`, or `rendition:page-spread-center` followed by `rendition:page-spread-left` [in RTL mode]) results in a small white box for the unpopulated viewport along with the inability to navigate past that viewport:
![Right spread left unpopulated screenshot](https://github.com/johnfactotum/foliate/assets/3128050/80098d30-1c3f-4050-8040-77f290223dfa)
In the above screenshot, the left viewport is left unpopulated by having page 3 (P-03) declared as `rendition:page-spread-right` and having page 4 (P-04, not shown above) declared as `rendition:page-spread-center` in the spine `itemref`. Attempt to navigate forward/next past the unpopulated viewport is broken (i.e. does not advance viewer) but navigating back/previous works as expected.<br/>
![Left spread right unpopulated screenshot](https://github.com/johnfactotum/foliate/assets/3128050/48c03c33-a351-49f0-95a3-b3b38256f920)
The same is true for an unpopulated right viewport with the same symptoms as the previous example but with an inability to navigate back/previous, but navigating forward/next works.

4. Center spread does not use the entire renderer's dimensions, resulting in an overly small spread:
![Center spread screenshot](https://github.com/johnfactotum/foliate/assets/3128050/9886eb20-fafd-4a05-8c57-60a6c05de75a)
The viewport dimensions for a center spread seems to be limited to that of a single 'side' (i.e. left/right) spread, resulting in a landscape page (typical of pages marked with `rendition:page-spread-center`) to be rendered overly small.

5. Cannot open books from the library that are fixed-layout RTL:
![Library screenshot](https://github.com/johnfactotum/foliate/assets/3128050/8fed68b2-9b2f-4349-bab7-21d836b780fc)
All books that are fixed-layout RTL show up as blanks in the library that fail to open:
![Book cannot open screenshot](https://github.com/johnfactotum/foliate/assets/3128050/7b032cda-71f5-4b93-927a-195990d6dd21)
The only way to get them opened in the first place is to directly open the EPUB with the application. The example book does have a correctly tagged cover page that does correctly show up in the "About this book" dialog box (in the renderer).

**To Reproduce**
1. Download [FXL-Test.zip](https://github.com/johnfactotum/foliate/files/12508126/FXL-Test.zip)
2. Extract and open `FXL-Test.epub` from the archive.

*Note:* The provided EPUB document does contain a few additional metadata and language tag tests (that trip up other readers like Thorium) but passes `epubcheck` with 0 warnings or errors. If an absolute minimal EPUB file that triggers all the bugs denoted here without the additional (unrelated) tests is desired, one can be provided. An example of a language-tag rendering issue in Thorium is shown [here](https://github.com/edrlab/thorium-reader/issues/1987).

**Expected behavior**
The following screenshots represent the hypothetical correct rendering of the test EPUB document exhibited above:
<p align="center" width="100%"><img src="https://github.com/johnfactotum/foliate/assets/3128050/2c92442f-21d4-482f-8c9e-ff7a755daf65" width="50%" /></p>

![Pages 01-02 screenshot](https://github.com/johnfactotum/foliate/assets/3128050/87b6e0a6-cb29-4b52-951a-f43de4665977)
![Page 03 screenshot](https://github.com/johnfactotum/foliate/assets/3128050/b1e3ca90-b2ba-4435-9484-da25fcb51786)
![Page 04 screenshot](https://github.com/johnfactotum/foliate/assets/3128050/b31b6ab6-94bd-428a-81b2-6b0d139db613)
![Page 05 screenshot](https://github.com/johnfactotum/foliate/assets/3128050/cd741d3f-3d5f-4fcf-ae7d-18276477b115)
![Pages 06-07 screenshot](https://github.com/johnfactotum/foliate/assets/3128050/542ab97a-07c2-4889-b03d-4c9cff65b578)

<p align="center" width="100%"><img src="https://github.com/johnfactotum/foliate/assets/3128050/31992b22-c792-4404-b000-5ced4f52e2cf" width="50%" /></p>

**Version:**
 - Foliate version: efddb107ae3c3a7c3acca73ad0c6a19981234e04
 - OS/Distribution and version: Arch Linux (kernel: 6.4.12-arch1-1, GTK4: 4.12.1, GJS: 1.76.2)
 - Desktop environment: KDE 5
 - Installation method: AUR/Manual build

**Additional information:**
[epub.js](https://github.com/futurepress/epub.js) has significant issues with rendering RTL fixed-layout document that cause much more severe rendering issues than what is described here (with appropriate bug reports opened for them), hence this bug report targeting the GTK4 branch and foliate-js, since the codebase for that renderer should be under this project's control.

**Comment by johnfactotum** [comment]
Fixed with https://github.com/johnfactotum/foliate-js/commit/99e246ecb854a1b3c5116c21b1faacd1342ff030 and https://github.com/johnfactotum/foliate-js/commit/0cebcb93c43bab53013c75823bebe69b1d531766. 

> center gap between the two pages

I think this is due to the default margin on the body element, which can be fixed with `body { margin: 0; }`.

**Comment by initramfs** [comment]
This might be an extremely minor nitpick but even with `margin: 0; padding: 0` on the `html` and `body` elements there still exists a 1 pixel gap between the spreads:
![CSS spread gap screenshot](https://github.com/johnfactotum/foliate/assets/3128050/6ee3d960-1632-41e4-8b68-f27392d6f286)

[Thorium](https://github.com/edrlab/thorium-reader) renders both variants (stylesheet-less and with stylesheet) as truly gapless:
![Thorium spread gap screenshot](https://github.com/johnfactotum/foliate/assets/3128050/167daf41-6677-49e4-9aac-9a75abdf167c)

---

Relevant EPUBs here (contains original EPUB + EPUB with stylesheet): [FXL-Test.zip](https://github.com/johnfactotum/foliate/files/12565776/FXL-Test.zip)

On another note: I'm not well versed with any specifications of default values for CSS properties besides what is shown [here](https://www.w3schools.com/cssref/css_default_values.php) (I'm not sure if this is normative), but should the body margin be set to 0 px for FXL content?

**Comment by johnfactotum** [comment]
A slight gap is visible in your Thorium screenshot as well. I think it's an antialiasing artifact (antialiasing being applied to the individual pages which causes the gap to appear). As far as I know it's not really something that can be fixed as the antialiasing is controlled by the browser engine. It works for me, though, when using 200% HiDPI scaling:

![Screenshot from 2023-09-10 17-31-43](https://github.com/johnfactotum/foliate/assets/50942278/0d163173-8c12-42a6-bf2f-2afb64080f05)

Regarding the default user agent stylesheet, as far as I can tell, there aren't any special requirements for fixed layout. For EPUB in general, the [reading system spec](https://www.w3.org/TR/epub-rs-33/) says

> a reading system's user agent style sheet SHOULD support the [[html](https://www.w3.org/TR/epub-rs-33/#bib-html)] [suggested default rendering](https://html.spec.whatwg.org/multipage/#rendering).

**Comment by initramfs** [comment]
Okay, I can reproduce the gapless rendering with 200% scale as well, also noticed Thorium's gapless rendering might have a bug as well (where the pages are actually overlapped by 1 or 2 pixels, producing the AA artifacts), though that's hard to confirm (increasing zoom level causes pages to definitively overlap on my system though).

In any case, thanks for fixing this bug, seems to be the only FOSS epub renderer right now that can actually render FXL RTL correctly.
