### ISSUE TITLE
Foliate stopped working on Ubuntu 22.04

### ISSUE THREAD

**Issue by tomicakorac** [johnfactotum/foliate#879]
**Describe the bug**
The Foliate application stops responding, and becomes unusable after a couple seconds.

**To Reproduce**
1. Open Foliate
2. Open any ebook (tried with numerous files of .epub format)
3. Attempt to use any piece of user interface
4. Foliate does not respond - does nothing

**Expected behavior**
User interface should respond as expected to the user interaction. For example, when I click on the right side, pages should turn forward, left side pages should turn back, moving page slider should move book pages appropriately, clicking content headings should jump to corresponding section etc.

**Version:**
 - Foliate version: 2.6.3, 2.6.4
 - OS/Distribution and version: Ubuntu 22.04
 - Desktop environment: GNOME Shell 40.alpha, GNOME Shell 40.beta
 - Installation method: Ubuntu PPT / apt, snap

**Additional context**
Foliate was working just fine before, but I am not sure exactly at which point it started malfunctioning. I'm suspecting this happened after upgrading from Ubuntu 21.10 to 22.04.

**Comment by amirHHP** [comment]
I have same problem after upgrade to 22.04.

**Comment by openmindead** [comment]
On my side there's a bit different issue: Foliate just won't open any epub I try.
Both Ubuntu and Arch versions.

**Comment by Streppel** [comment]
Just stumbled upon this. Trying to start from command line outputs

`❯ foliate         
Gtk-Message: 15:42:24.916: Failed to load module "canberra-gtk-module"Gtk-Message: 15:42:24.918: Failed to load module "canberra-gtk-module"** (com.github.johnfactotum.Foliate:12663): WARNING **: 15:42:25.023: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied** (com.github.johnfactotum.Foliate:12663): WARNING **: 15:42:25.023: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied

** (com.github.johnfactotum.Foliate:12663): ERROR **: 15:42:25.027: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
[1]    12663 trace trap (core dumped)  foliate`

**Comment by Lagrang** [comment]
Same problem on Ubuntu 20.04
```
** (com.github.johnfactotum.Foliate:1173356): ERROR **: 20:03:01.073: Unable to fork a new child process: Failed to execute child process “/usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/WebKitNetworkProcess” (No such file or directory)
```

**Comment by apandada1** [comment]
I cannot reproduce the issue in **Xubuntu** 22.04 with the PPA version of Foliate. It runs just fine.

**Comment by bpint** [comment]
Same here. There is a workaround. When you login, choose 'Ubuntu on xorg' instead of 'Ubuntu', and you will get a functional Foliate.

**Comment by tomicakorac** [comment]
Hm, that is really strange. I am in fact using Ubuntu on Xorg, and I am still experiencing the same issue - Foliate is practically unusable.

**Comment by lorezcrash** [comment]
No tricks work for me because it crashes on load, every time. No error message. Just starts to load and then never does.

**Comment by openmindead** [comment]
Here's what I see when I launch Foliate with `--verbose` flag:
```
(com.github.johnfactotum.Foliate:5843): dbind-WARNING **: 00:43:53.123: AT-SPI: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files

(com.github.johnfactotum.Foliate:5843): Gjs-WARNING **: 00:43:53.309: JS ERROR: Error: File type not supported.
_init/<@resource:///com/github/johnfactotum/Foliate/js/epubView.js:623:57
open@resource:///com/github/johnfactotum/Foliate/js/epubView.js:1162:27
async*open@resource:///com/github/johnfactotum/Foliate/js/window.js:1033:20
_init@resource:///com/github/johnfactotum/Foliate/js/window.js:987:29
Window@resource:///com/github/johnfactotum/Foliate/js/window.js:906:4
main/<@resource:///com/github/johnfactotum/Foliate/js/main.js:255:22
main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
@/usr/bin/foliate:9:17
```

Both Ubuntu (Gnome Wayland) and Manjaro (Plasma Wayland and X11).

**Comment by uriel1998** [comment]
Similar problem, Debian 11, glibc 2.72, installed from .deb package.

Interestingly, the same version of foliate, but flatpak (installed via [bauh](https://github.com/vinifmor/bauh)], works just fine. Which isn't a *solution*, but perhaps a short-term workaround for some other folks.

**Comment by johnfactotum** [comment]
@uriel1998 If you're seeing "Empty Response", that's #885. The Flatpak version is still using the GNOME 41 runtime so it probably has glib < 2.72.

**Comment by tomicakorac** [comment]
So is there any hope that this gets fixed now? Or that we at least get a response from the maintainer?

**Comment by apandada1** [comment]
Cannot reproduce on Ubuntu MATE 22.04. Is this issue GNOME specific?

**Comment by tomicakorac** [comment]
Yes, this is specific to GNOME.

**Comment by tomicakorac** [comment]
@apandada1 since you are marked as the Ubuntu package maintainer, is there a chance you look into this issue any time soon?

@johnfactotum if we do not get any responce from @apandada1, what other options do we have to have this fixed? Foliate is basically unusable for over half a year now.

**Comment by apandada1** [comment]
@tomicakorac I don't know how to fix the bug, but does deleting mime.cache help, as in #878 ?
Also, can you check if Atril can open epubs in Ubuntu 22.04? Someone found that it is also affected by the same bug, in Arch Linux.

Moreover, last time I checked in a VM, Foliate was working in MATE and XFCE.

**Comment by tomicakorac** [comment]
Thank you @apandada1.

Deleting `~/.local/share/mime/mime.cache` did not change anything, the issues remain.

I've never used Atril, so can't know for sure. On the first glance, it looks like Atril works just fine, no issues. On the other hand, Atril is a completely different product and is not related to Foliate. Its user preferences are very limited compared to Foliate, and Atril can not replace Foliate for me.

MATE and XFCE don't have anything to do with this bug, this is specific to GNOME Shell version 40, as indicated in the initial bug report, and confirmed by several users in this thread.

Judging from the direction this discussion is going in, I am very sorry to conclude that Foliate on Ubuntu is a dead project now. What a shame.

**Comment by Nicolaith** [comment]
Google founds a lot of cases with the same error "run@resource:///org/gnome/gjs/modules/script/package.js:206:19" after upgrade to Gnome shell 40
There also is a guide to port extensions - https://gjs.guide/extensions/upgrading/gnome-shell-40.html , maybe it can help?

**Comment by tomicakorac** [comment]
Just now I've realised something that might be useful: As described above, Foliate does not accept user commands (or doesn't accept them accurately), but as soon as you change focus from Foliate to anything outside of Foliate (e.g. switch to another app window, or open Gnome menu, or open Activities menu, anything really that is outside of Foliate), Foliate will actually execute the last commands.

**Comment by tomicakorac** [comment]
Additional potentially useful detail: This issue consistently exists on regular users' accounts (both admin and user levels), but does not exist on the root account. When I run `sudo com.github.johnfactotum.Foliate' the app instance does not experience any problems. I can't conclude what may be the reason.

**Comment by tomicakorac** [comment]
Some more details that I hope can help fix this. After discovering that the problem doesn't occur when Foliate is run as Root, I ran the app from the terminal as both non-root and root, using `--verbose` flag. The log shows that as non-root, this section never gets run:

```
rendition-ready
run_javascript: setStyle({"fontFamily":"Serif","fontSize":16,"fontWeight":400,"fontStyle":"normal","fontStretch":"normal","spacing":1.5,"margin":40,"maxWidth":1400,"usePublisherFont":false,"justify":true,"hyphenate":...
run_javascript: setupRendition()
run_javascript: display('epubcfi(/6/36!/4/2/18/14/2/2/2/1:0)')
layout
book-displayed
relocated
epubcfi(/6/36!/4/2/18/14/2/2/2/1:0)
```

As mentioned before, this only gets run after Foliate loses and regains focus.

**Comment by tomicakorac** [comment]
This is the warning after which Foliate becomes unrespnosive:

`
(com.github.johnfactotum.Foliate:15965): Gjs-WARNING **: 11:51:16.013: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  main@resource:///com/github/johnfactotum/Foliate/js/main.js:478:24
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  @/usr/bin/com.github.johnfactotum.Foliate:9:17
`

**Comment by tomicakorac** [comment]
Attaching logs for comparison:
- `foliate-log-user.txt` is the regular user's log, where the errors do occur
- `foliate-log-sudo.txt` is the sudo user's log, where there are no such error
[foliate-log-sudo.txt](https://github.com/johnfactotum/foliate/files/9173220/foliate-log-sudo.txt)
[foliate-log-user.txt](https://github.com/johnfactotum/foliate/files/9173221/foliate-log-user.txt)
s

**Comment by Nicolaith** [comment]
Finally, it works again since I deleted the file ~/.local/share/mime/mime.cache

**Comment by tomicakorac** [comment]
@Nicolaith I'm very happy to hear there's hope. I've deleted that file and still no joy :( Should I re-create `mime.cache` after it's deleted?

**Comment by kaia009** [comment]
I just did a fresh Jammy install and ran into Foliate errors including the ones mentioned in this thread. Then I remembered: The  first time I installed Jammy (on another computer)  several  months ago, the first thing I did was to check whether Wayland was causing the trouble, so I rebooted to Jammy using the Ubuntu on Xorg option. There were no problems on Xorg. What was odd, though, was that when I rebooted into Jammy with wayland, Foliate was absolutely fine. 

So today, I did the same thing: 
1) Rebooted using the "Ubuntu on Xorg" option before entering log-in details  (a little wheel bottom right)
2) Tested Foliate 
3) Rebooted  making sure to change back to standard "Ubuntu"
Foliate was fine. 
Hopes this helps somebody.

**Comment by tomicakorac** [comment]
@kaia009 your steps don't work for me. I actually don't run Wayland at all, I've been on Xorg all the time, and I'm still experiencing the same issue.

On my system I have several desktop environments installed: Gnome, Old Gnome (Compiz), Old Gnome (Metacity), Gnome on XServer, Ubuntu (Wayland), Ubuntu on Xorg. I've tried each and every one of them, and the same issue persists everywhere.

Further more, I've created a completely new user, just to test Foliate, tried logging in new user with all of the above environments, just to ensure the bugs aren't caused by my primary account user settings. Again, all issues persisted. I'm hopeless.

I do have a question though, @kaia009. Why did you reboot your computer when changing desktop environments? Is this step necessary? Wasn't it enough to log out and choose a new desktop environment on log in?

**Comment by kaia009** [comment]
Very sorry to hear of your plight. 
You're probably right about the rebooting, though. It would probably have been enough to just log out.

**Comment by jhncondix** [comment]
Same on Pop!_OS 22.04. Debian package version hangs and never loads a book. The Flatpak version works but throws errors about "Failed to load module canberra-gtk" and so forth.

**Comment by tomicakorac** [comment]
GNOME Shell got updated on my machine today to the version `43.beta`, and the situation got even worse. Even more issues are manifesting. How on Earth is it possible that this problem is still not receiving any attention @johnfactotum? Foliate in inoperable on the single most used Linux distribution for over half a year, surely this should ring all the emergency bells.

**Comment by johnfactotum** [comment]
I'm sorry to hear that. Unfortunately I do not have much time for developing Foliate right now. I did look at the logs and I don't see anything useful. It looks like it runs fine up until the book is actually being rendered, but somehow the events just never fires. That and the fact that simply changing the focus could make it work reminds me of bugs like #94. These are the kind of mysterious bugs that lie somewhere between GTK, WebKitGTK, and Epub.js that I can never really figure out. The strangest thing is that, it would appear that the book is actually being rendered properly, but somehow Epub.js doesn't know that. The logical explanation would be that Epub.js depends on receiving certain sizing information or resize events before it could report that it has rendered the book, but whatever that's providing that information or event isn't function properly under certain conditions, probably also related to the way the webview is set up. The problem is that at this point it is still unclear what those conditions are.

**Comment by lorezcrash** [comment]
@johnfactotum any interest in bringing anyone else onto the project to maintain development?

**Comment by johnfactotum** [comment]
I'm still actively managing this project but I won't be making any sweeping changes to the 2.x versions. People are welcome to make PRs. I will be working on the next major version, which is porting Foliate to GTK 4 and replacing Epub.js and KindleUnpack.

**Comment by bugraonal** [comment]
I had the same warning as @tomicakorac. Running Foliate with G_MESSAGES_DEBUG=all I got this message:

`(com.github.johnfactotum.Foliate:147859): Foliate-DEBUG: 18:24:31.122: writing to /home/bugra/.local/share/com.github.johnfactotum.Foliate/urn%3Auuid%3Abcb88ccb-7abc-469d-a556-e511229c3075.json`

Removing this JSON file fixed it for me.

**Comment by johnfactotum** [comment]
@bugraonal Did you backup that JSON file, by any chance? Can you reproduce the issue by putting it back?

**Comment by bugraonal** [comment]
@johnfactotum I did not, sadly. And it seems, it has been replaced by a new version which doesn't seem to cause any issues.

**Comment by lbassuncao** [comment]
> ~/.local/share/mime/mime.cache

On Ubuntu 22.04.1, deleting the cache worked for me. Thanks.

**Comment by anutator** [comment]
deleting the cache works but for some time. Then I have to delete cache again.

**Comment by tomicakorac** [comment]
@johnfactotum 's comment in #962 made me curious again. He thinks these issues might arise from malfunctioning of WebkitGTK. Looking around my system I noticed the following:

- I do not have installed any package named WebkitGTK (I'm running Ubuntu 22.10);
- I do have several versions of `libwebkit2gtk` package installed, namely 4.0. 4.1 & 5.0; From this package's description, this package is `Web content engine library for GTK`; Am I right to understand that in Ubuntu world, libwebkit2gtk is equivalent to WbkitGTK generic package?
- As mentioned, there are 3 versions of this package installed; I can't uninstall any of these versions, because apparently a large number of system critical packages dipend on each of these versions;
- Foliate seems to be using the 4.0 version - or at least it depends on it (if I attempt to purge `libwebkit2gtk-4.0-37` package, `com.github.johnfactotum.foliate` is listed as one of the packages that will also be removed;

Is it possible to make Foliate use a different version of libwebkit2gtk package? Can I somehow make it use version 5.0*? How likely is it that this might fix any of the above issues?

**Comment by johnfactotum** [comment]
Honestly I think perhaps the best way to debug your issue would be to try one of the 1.x versions of Foliate. If it works, try to do a git bisect (or just manually try other different versions) to find the culprit.

If not even the 1.x versions work, the best way would be to try to make a minimal GTK window with a WebView, and load a very minimal Epub.js page, and go from there.

**Comment by tomicakorac** [comment]
Thank you for the suggestion John. Sadly, even 1.x versions are showing the same set of issues for me. At least from 1.4 and above, as lower versions don't have .deb packages ready.

> If not even the 1.x versions work, the best way would be to try to make a minimal GTK window with a WebView, and load a very minimal Epub.js page, and go from there.

I would be happy to try this, but I'm sorry to say I'm not a programmer and don't really understand how I would go about doing this. That said, I'll still give it my best try.

**Comment by johnfactotum** [comment]
Well, I guess one could go with something like this
```js
imports.gi.versions.Gtk = '3.0'
imports.gi.versions.WebKit2 = '4.0'
const { Gtk, Gio, GLib, WebKit2 } = imports.gi
const app = new Gtk.Application({ application_id: 'com.github.johnfactotum.Foliate' })
app.connect('activate', () => {
    const win = new Gtk.ApplicationWindow({
        application: app,
        default_width: 900,
        default_height: 600,
    })
    const webView = new WebKit2.WebView()
    win.add(webView)
    webView.load_uri('https://johnfactotum.github.io/foliate-js/reader.html')
    win.show_all()
})
app.run([])
```

Run the file with `gjs`.

In the `.load_uri()` function, it loads the new renderer's demo. You can change it to anything.

So e.g. change it to https://futurepress.github.io/epub.js/examples/input.html to test Epub.js.

If this works, then I guess one could debug by building the 1.0.0 version, and try to remove some code at a time until it works. I'm afraid I can't think of another way. (Well, you could do it in the opposite direction. Which basically amounts to recreating Foliate from scratch until it breaks. So it's not really easier.)

**Comment by tomicakorac** [comment]
Amazing, you're a start. I'll test this today.

Opening https://futurepress.github.io/epub.js/examples/input.html in any browser I have available (Vivaldi, Epiphany, Firefox, Chromium) does show several issues loosly similar to the ones described here - hanging on load, unable to scroll pages, a few others. I'm really not sure how relevant this is, but there is clearly something wrong ith Epub.js.

None of these issues exist at https://johnfactotum.github.io/foliate-js/reader.html at least not in the web browsers. I'll continue testing John's script, but my hopes are still live that foliate-js renderer might help resolve this report.

**Comment by tomicakorac** [comment]
After the first round of testing:

Summary: Basically, the script gives the exact same results as all the browsers. foliate-js seems to be working ok, at least those features that are currently available, while epub.js is practically unusable.

### Foliate.js

Tested:
- The interface loads properly, no infinite loading until focus change;
- Epub file loads properly, again no infinite loading until focus change;
- Forward/backward buttons work as expected, even while clicked very quickly;
- Chapter menu works - clicking any Chapter name in the Chapter menu moves the ebook to the selected Chapter;

Not tested:
- Mouse scroll;
- Keyboard navigation;
- Progress bar slider;

### Epub.js

Tested:
- Interface shows loading animation which doesn't go away until a file is loaded;
- Epub file *seems to be* loading properly; In fact, only the first (cover) page can be seen, since page navigation doesn't work;
- Forward/backward buttons do not work - it is impossible to change pages;
- Mouse scroll does not work (is this expected?;
- Keyboard navigation does not work (is this expected?);

Not tested:
- Chapter menu (doesn't exist);
- Progress bar slider;

**Comment by tomicakorac** [comment]
To compare with the above test, all Epub.js examples from this address work absolutely fine:

https://futurepress.github.io/epub.js/examples/

**Comment by tomicakorac** [comment]
Ok, wow... I think I was finally able to fix this problem. It is indeed related to `mime.cache` file. BUT...

- In Ubuntu there are two `mime.cache` files. not one.
- It was not enough for me to just delete `mime.cache`, as indicated in this thread. I had to update the mime database.

For future reference, this seems to have helped:

```
$ rm ~/.local/share/mime/mime.cache
$ update-mime-database ~/.local/share/mime
$ sudo rm /usr/share/mime/mime.cache
$ sudo update-mime-database /usr/share/mime
```

In my case, it seems that the only one causing the problem was `/usr/share/mime/mime.cache`, but there's no harm in doing the same for `~/.local/share/mime/mime.cache`.

I wonder how none of the thread participants thought of suggesting this before.

I'll continue testing for final confirmation, but I'm closing this thread for now. If needed, I'll reopen it.

**Comment by johnfactotum** [comment]
> Epub file seems to be loading properly; In fact, only the first (cover) page can be seen, since page navigation doesn't work;

Sorry, I keep forgetting that the version on Epub.js's website is broken (https://github.com/futurepress/epub.js/issues/1066). The problem has been fixed (https://github.com/futurepress/epub.js/pull/949) for some while. It just appears that the website branch (https://github.com/futurepress/epub.js/tree/gh-pages) hasn't been updated since 2018.

**Comment by tomicakorac** [comment]
Thank you very much for the time, patience and suggestions @johnfactotum. I confirm that `sudo update-mime-database /usr/share/mime` fixed the issue for me completely.

For others, the problem might also be caused by `~/.local/share/mime.cache` file.

I always say that all is well that ends well, but I still got irrationally angry this morning after finding out that such a simple solution fixed the issue that's been causing me aggrevation for more than 6 months.

**Comment by tomicakorac** [comment]
Ugh, my problem is back! After almost 2 days working normally, I can't open any ebook again. This time, the commands I thought had resolved my problem are not helping. This is terrible :sob:

**Comment by johnfactotum** [comment]
I have no idea, honestly. Perhaps you can also try posting on https://discourse.gnome.org/.

**Comment by apandada1** [comment]
I can reproduce this on a VM running Ubuntu 22.04 (no NVidia drivers). Only occurs in the "power saver" mode. 
I could not reproduce this bug in any other Ubuntu flavor (including GTK based DEs like MATE, XFCE or Unity).

**Comment by johnfactotum** [comment]
Just a guess: perhaps it has something to do with the WebView (or one of its ancestor widgets) has zero opacity. I mean that sounds like something that might get optimized when in power saver mode, right? If that's what's causing the problem then it could be fixed by deleting this line: https://github.com/johnfactotum/foliate/blob/1f11b9bb918beea5da7268f72acb2cf1114ef27b/src/ui/mainOverlay.ui#L205
And maybe also this line:
https://github.com/johnfactotum/foliate/blob/1f11b9bb918beea5da7268f72acb2cf1114ef27b/src/window.js#L493

**Comment by apandada1** [comment]
I removed the lines in https://github.com/johnfactotum/foliate/issues/879#issuecomment-1292443667, and it seems to work in virtualbox (however, Foliate takes ~10 seconds to load in the power saver mode).
@tomicakorac I made a PPA with this patch. https://launchpad.net/~apandada1/+archive/ubuntu/foliate-experiments Please verify if the it works.

**Comment by tomicakorac** [comment]
Thanks for the quick reaction guys.

@apandada1 that's a negative. Unfortunately the experimental version did not fix the problem on my computer, it only made it a little different, but essentially all the same issues still remain.

Honestly, now that we are 100% certain of the culprit -- and we have a really simple workaround (just change power profile to 'balanced' or 'performance') -- I can live with this. It would be great to fix this bug, but I assume its priority is far lower than much of the other workload @johnfactotum has already.

Also, Ubuntu's (or more precisely, GNOME's) Power Profiles feature is fairly new, poorly documented and nobody seems to know precisely how the feature works, i.e. what exactly do the profiles do to the system. I think it would be difficult to proceed with the debugging until we understand this first. I've raised an issue in the [Power Profiles Daemon Gitlab repository](https://gitlab.freedesktop.org/hadess/power-profiles-daemon/-/issues/113) and will update you as I receive new information.

Lastly, since this whole thread has become a wreck, containing outdated (and potentially even harmful) assumptions, I suggest that we close it now. I will open a new issue with a more precise bug report, for future tracking, and I suggest that it is addressed with relatively low priority (of course, if anyone disagrees, feel free to say so).

**Comment by wimdows** [comment]
The same problem also occurs on the Librem5 running PureOS. It does not have a Power Saver Mode.

**Comment by kaia009** [comment]
I have Ubuntu 22.04 running on no less than three laptops (Huawei and Samsung). On all three, Foliate is working beautifully, BUT their doing so required preliminary steps that I have described in a previous post. 

I admit that the few steps I took seem illogical, and I cannot explain why they worked. But, I insist,  they had to be repeated for all three laptops. 

1) I installed using the PPA
sudo add-apt-repository ppa:apandada1/foliate

I started Foliate and it did not perform properly. 

2) I restarted Ubuntu with Xorg (i.e. at restart, before entering the password, press the settings wheel bottom right, and choose Xorg to disable Wayland.)

I started Foliate and it worked perfectly. 

3) I restarted Ubuntu and made sure that Xorg was not chosen.

I started Foliate, and it worked perfectly (in Wayland)
***
True there is one issue: I can "export annotations" to JSON, HTML and plaintext (have not tried the other options), but I cannot "import annotations" from JSON. To move my annotations to another computer I have to physically copy/paste them between the following directory of the two computers.

 /.local/share/com.github.johnfactotum.Foliate
 
 I was in fact reading a book on Foliate until I was interrupted by recent mail in this thread. Foliate was working beautifully tonight, 23 April, on Ubuntu 22.04 as it has been working beautifully for me ever since I performed the above steps.

**Comment by tomicakorac** [comment]
@kaia009 from your work-around steps it looks to me like they can't be used for anyone who is not on Wayland, correct? For example, I use Ubuntu on Xorg as my default environment, I can't change from Xorg to Wayland and stay there.

**Comment by nomadbl** [comment]
I may have found another workaround (or missed it in this huge thread):
**Open foliate on its own and then open whatever file.**
I got the bug initially when opening a file with foliate from the file manager.

**System info:**
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
window manager/system: GNOME 42.9 on Wayland
Mesa Intel® UHD Graphics (ICL GT1)
installed foliate with snap

**Comment by David-Duffy** [comment]
To be boring (it's now 2024!) - this used to work for me until fairly recently but

A tower PC on AC power, I can't find any relevant CPU power management utilities installed
Linux tinonee 5.15.0-105-generic #115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 22.04.4 LTS (jammy)
Xubuntu Xfce 4.16

> foliate

Library pane comes up OK but once select an epub,
The contents bar is OK but the text pane is blank, and the following messages are emitted:

** (com.github.johnfactotum.Foliate:7218): WARNING **: 14:35:14.192: Could not open /sys/class/dmi/id/chassis_type: Failed to open file “/sys/class/dmi/id/chassis_type”: Permission denied
** (com.github.johnfactotum.Foliate:7218): WARNING **: 14:35:14.192: Could not open /sys/firmware/acpi/pm_profile: Failed to open file “/sys/firmware/acpi/pm_profile”: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 900x750: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 900x750: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 900x750: Permission denied
Failed to create EGL images for DMABufs with file descriptors -1, -1 and -1

Furthermore, the invisible text can be selected and copied. 

1) At least some of these error messages are similar to those reported earlier for this (#879)
2) The same behaviour now appears for the Liferea RSS program

**Comment by archisman-panigrahi** [comment]
@David-Duffy How did you install foliate? As a workaround, can you try another installation method?

**Comment by alizshow** [comment]
Using an nvidia card and the proprietary `nvidia-535` on Ubuntu 24.04.

I also have these warnings which are likely unimportant and can be ignored:
- `Requiring Tracker`
- `/sys/class/dmi/id/chassis_type`
- `/sys/firmware/acpi/pm_profile`

Following [this post](https://forums.gentoo.org/viewtopic-p-8809138.html?sid=4557e59c326fcfebef9565c6b1fa9861), setting this variable when calling foliate solved my problem:
```
WEBKIT_DISABLE_DMABUF_RENDERER=1
```

copied the snap desktop file

```
cp /var/lib/snapd/desktop/applications/foliate_foliate.desktop ~/.local/share/applications/
```

and added the env value by editing the desktop Exec line
mine looks like this.

```
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/foliate_foliate.desktop env WEBKIT_DISABLE_DMABUF_RENDERER=1 /snap/bin/foliate %U
```

then used ALT+F2 and run the gnome-shell command `restart` to reload applications.
